; PlatformIO Project Configuration File for ESP32 ENCODER (Slave Node)
[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -DSIMULATION_MODE=1
    -D CORE_DEBUG_LEVEL=1
