; PlatformIO Project Configuration File

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.filesystem = littlefs

build_flags =
    -DSIMULATION_MODE=1
    -D CORE_DEBUG_LEVEL=1
    ; -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000   ; descomenta si tienes problemas de estabilidad

lib_deps =
    ESP32Async/AsyncTCP @ ^3.3.0
    ESP32Async/ESPAsyncWebServer @ ^3.6.0
    bblanchon/ArduinoJson @ ^7.1.0